version: "3.9"

services:
  db:
    image: postgres:14.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG=true
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - /Users/kotelnikov/Documents/projects/get_slides:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db

