version: "3.9"

services:
  db:
    image: postgres:14.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG=true
    ports:
      - 5432:5432
  web:
    build: .
    environment:
      - FLASK_APP=src/server
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db

